# PLACE THIS FILE IN FOLDER WHERE YOU KEEP hyperflow AND hyperflow-job-executor REPOS

version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  hyperflow:
    image:  hyperflowwms/hyperflow:v1.4-dev
    tty: true
    environment:
      - REDIS_URL=redis://redis/
      - HF_VAR_function=redisCommand
    volumes:
      - /Users/lwronski/projects/splunk-otel-network-explorer-chart:/kernel
      - ./wfdir:/home/wfdir
      - ./hyperflow/:/home/hyperflow/
      - ./hyperflow-job-executor/:/home/hyperflow-job-executor/
    networks:
      - my-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - my-network
  
  collector-gateway:
   image: otel/opentelemetry-collector:0.68.0
   volumes:
     - ./collector-gateway.yaml:/etc/collector-gateway.yaml
   command: [ "--config=/etc/collector-gateway.yaml" ]
   ports:
     - "1888:1888"   # pprof extension
     - "13133:13133" # health_check extension
     - "4317:4317"        # OTLP gRPC receiver
     - "4318:4318"        # OTLP HTTP receiver
     - "55670:55679" # zpages extension
   depends_on:
     - jaeger
   networks:
     - my-network

  reducer:
    image: quay.io/signalfx/splunk-network-explorer-reducer@sha256:9db4db0c4c420a344cb971f895851ebf4c75373d6857030a513ac4a2a7621aa7
    entrypoint: /srv/opentelemetry-ebpf-reducer --disable-prometheus-metrics --enable-otlp-grpc-metrics --otlp-grpc-metrics-host=collector-gateway --log-whitelist-all
    ports:
      - "8000:8000"
    networks:
      - my-network
  
  ubuntu-1:
    image: ubuntu
    tty: true
    privileged: true
    pid: "host"
    networks:
      - my-network
    volumes:
      - /Users/lwronski/projects/splunk-otel-network-explorer-chart:/kernel

networks:
    my-network:
      driver: host